<?php

/**
 * @file
 *
 * PDF Views allows the creation of PDF's directly from a view. Without the
 * creation of HTML first.
 */

xautoload()->registerModulePsr4(__FILE__, 'src');
_xautoload_register_drupal();

/**
 * Implements hook_views_api().
 */
function views_pdf_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_libraries_info().
 */
function views_pdf_libraries_info() {
  $libraries = array();

  // PSR-0 Load, and vendor tcpdf
  // To complete the full install you need to run `composer install`.
  $libraries['fpdi_tcpdf'] = array(
    'name'              => 'FPDI_TCPDF library',
    'vendor url'        => 'https://github.com/onigoetz/fpdi_tcpdf',
    'download url'      => 'https://github.com/onigoetz/fpdi_tcpdf/archive/master.zip',
    'version arguments' => array(
      'file'    => 'src/fpdi/FPDI.php',
      'pattern' => '@Version\s+([0-9a-zA-Z\.-]+)@',
      'lines'   => 3,
    ),
    'files'             => array(
      'php' => array(
        'src/fpdi_tcpdf/FPDI.php',
        'src/fpdi_tcpdf/FPDF.php',
        'vendor/tecnick.com/tcpdf/tcpdf.php',
      ),
    ),
    'xautoload' => function($api) {
      $api->addPsr4('fpdi', 'src');
      $api->composerDir('vendor/composer');
    }
  );

  $libraries['fpdi'] = array(
    'name'              => 'FPDI library',
    'vendor url'        => 'http://www.setasign.com/products/fpdi/about/',
    'download url'      => 'http://www.setasign.com/products/fpdi/downloads/',
    'version arguments' => array(
      'file'    => 'fpdi.php',
      'pattern' => '@Version\s+([0-9a-zA-Z\.-]+)@',
      'lines'   => 3,
    ),
    'files'             => array(
      'php' => array(
        'fpdi.php',
      ),
    ),
  );

  $libraries['tcpdf'] = array(
    'name'              => 'TCPDF library',
    'vendor url'        => 'http://www.tcpdf.org/',
    'download url'      => 'http://sourceforge.net/projects/tcpdf/files/',
    'path'              => 'src',
    'version arguments' => array(
      'file'    => 'tcpdf.php',
      'pattern' => '@Version\s+:\s+([0-9a-zA-Z\.-]+)@',
      'lines'   => 4,
    ),
    'files'             => array(
      'php' => array(
        'tcpdf.php',
      ),
    ),
  );

  $libraries['MPDF57'] = array(
    'name'              => 'mPDF library',
    'vendor url'        => 'http://www.mpdf1.com/mpdf',
    'download url'      => 'http://www.mpdf1.com/mpdf/index.php?page=Download',
    'version arguments' => array(
      'file'    => 'mpdf.php',
      'pattern' => '@Version:\s+([0-9a-zA-Z\.-]+)@',
      'lines'   => 5,
    ),
    'files'             => array(
      'php' => array(
        'mpdf.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_theme().
 */
function views_pdf_theme() {
  // TODO: Review all the themes and find clear user.
  return array(
    'views_pdf_plugin_style_table' => array(
      'render element' => 'form',
      'file'           => 'views_pdf.admin.inc',
    ),
    'views_pdf_icon'               => array(
      'render element' => 'form',
      'variables'      => array('url' => NULL, 'title' => NULL),
    ),
  );
}

/**
 * Theme function for the PDF icon of appended PDFs.
 */
function theme_views_pdf_icon($vars) {
  $title                          = $vars['title'];
  $path                           = $vars['path'];
  $options                        = $vars['options'];
  $options['html']                = TRUE;
  $options['attributes']['class'] = 'pdf-icon';

  $image_path = drupal_get_path('module', 'views_pdf') . '/images/pdf.png';
  $image      = theme('image', array(
      'path'  => $image_path,
      'title' => $title,
      'alt'   => $title
    )
  );

  if ($image) {
    return l($image, $path, $options);
  }
}
