<?php

/**
 * @file
 *
 * PDF Views allows the creation of PDF's directly from a view. Without the
 * creation of HTML first.
 */

xautoload()->registerModulePsr4(__FILE__, 'src');
// _xautoload_register_drupal();

use Drupal\views_pdf\ViewsPdfTemplate;

/**
 * Implements hook_views_api().
 */
function views_pdf_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_libraries_info().
 */
function views_pdf_libraries_info() {
  $libraries = array();

  $libraries['fpdi_tcpdf'] = array(
    'name'              => 'FPDI library',
    'vendor url'        => 'https://github.com/onigoetz/fpdi_tcpdf',
    'download url'      => 'https://github.com/onigoetz/fpdi_tcpdf/archive/master.zip',
    'path'              => 'src/fpdi',
    'version arguments' => array(
      'file'    => 'src/fpdi/FPDI.php',
      'pattern' => '@Version\s+([0-9a-zA-Z\.-]+)@',
      'lines'   => 3,
    ),
    'files'             => array(
      'php' => array(
        'FPDI.php',
        'FPDF.inc',
      ),
    ),
    'xautoload' => function($api) {
      $api->namespaceRoot('fpdi', 'src');
    }
  );

  $libraries['tcpdf'] = array(
    'name'              => 'TCPDF library',
    'vendor url'        => 'http://www.tcpdf.org/',
    'download url'      => 'http://sourceforge.net/projects/tcpdf/files/',
    'version arguments' => array(
      'file'    => 'tcpdf.php',
      'pattern' => '@Version\s+:\s+([0-9a-zA-Z\.-]+)@',
      'lines'   => 4,
    ),
    'files'             => array(
      'php' => array(
        'tcpdf.php',
      ),
    ),
  );

  $libraries['MPDF57'] = array(
    'name'              => 'mPDF library',
    'vendor url'        => 'http://www.mpdf1.com/mpdf',
    'download url'      => 'http://www.mpdf1.com/mpdf/index.php?page=Download',
    'version arguments' => array(
      'file'    => 'mpdf.php',
      'pattern' => '@Version:\s+([0-9a-zA-Z\.-]+)@',
      'lines'   => 5,
    ),
    'files'             => array(
      'php' => array(
        'mpdf.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_theme().
 */
function views_pdf_theme() {
  // TODO: Review all the themes and find clear user.
  return array(
    'views_pdf_plugin_style_table' => array(
      'render element' => 'form',
      'file'           => 'views_pdf.admin.inc',
    ),
    'views_pdf_icon'               => array(
      'render element' => 'form',
      'variables'      => array('url' => NULL, 'title' => NULL),
    ),
  );
}

/**
 * Theme function for the PDF icon of appended PDFs.
 */
function theme_views_pdf_icon($vars) {
  $title                          = $vars['title'];
  $path                           = $vars['path'];
  $options                        = $vars['options'];
  $options['html']                = TRUE;
  $options['attributes']['class'] = 'pdf-icon';

  $image_path = drupal_get_path('module', 'views_pdf') . '/images/pdf.png';
  $image      = theme('image', array(
      'path'  => $image_path,
      'title' => $title,
      'alt'   => $title
    )
  );

  if ($image) {
    return l($image, $path, $options);
  }
}

/**
 * This method returns all available hyphenation patterns (paths to files).
 */
function views_pdf_get_hyphenations() {

  return ViewsPdfTemplate::getAvailableHyphenatePatterns();
}

/**
 * This method can be used to return a list of possible page formats.
 */
function views_pdf_get_page_formats() {
  $format['custom']    = t('Custom');
  $format['4A0']       = '4A0';
  $format['2A0']       = '2A0';
  $format['A0']        = 'A0';
  $format['A1']        = 'A1';
  $format['A2']        = 'A2';
  $format['A3']        = 'A3';
  $format['A4']        = 'A4';
  $format['A5']        = 'A5';
  $format['A6']        = 'A6';
  $format['A7']        = 'A7';
  $format['A8']        = 'A8';
  $format['A9']        = 'A9';
  $format['A10']       = 'A10';
  $format['B0']        = 'B0';
  $format['B1']        = 'B1';
  $format['B2']        = 'B2';
  $format['B3']        = 'B3';
  $format['B4']        = 'B4';
  $format['B5']        = 'B5';
  $format['B6']        = 'B6';
  $format['B7']        = 'B7';
  $format['B8']        = 'B8';
  $format['B9']        = 'B9';
  $format['B10']       = 'B10';
  $format['C0']        = 'C0';
  $format['C1']        = 'C1';
  $format['C2']        = 'C2';
  $format['C3']        = 'C3';
  $format['C4']        = 'C4';
  $format['C5']        = 'C5';
  $format['C6']        = 'C6';
  $format['C7']        = 'C7';
  $format['C8']        = 'C8';
  $format['C9']        = 'C9';
  $format['C10']       = 'C10';
  $format['RA0']       = 'RA0';
  $format['RA1']       = 'RA1';
  $format['RA2']       = 'RA2';
  $format['RA3']       = 'RA3';
  $format['RA4']       = 'RA4';
  $format['SRA0']      = 'SRA0';
  $format['SRA1']      = 'SRA1';
  $format['SRA2']      = 'SRA2';
  $format['SRA3']      = 'SRA3';
  $format['SRA4']      = 'SRA4';
  $format['LETTER']    = 'LETTER';
  $format['LEGAL']     = 'LEGAL';
  $format['EXECUTIVE'] = 'EXECUTIVE';
  $format['FOLIO']     = 'FOLIO';
  $format['MEMO']      = 'MEMO';

  return $format;
}
